import QtQuick 2.0
import Sailfish.Silica 1.0
import "."
import "../js/Emoji.js" as Emoji

/*
 * One emoji, drawn as a picture.
 *
 * Sailfish's Qt is 5.6, which cannot draw a colour font, and the system
 * fonts know a few hundred emoji at most, in monochrome -- the rest are
 * empty boxes. So an emoji is a Twemoji picture wherever one is shipped
 * (qml/art/emoji/, generated by scripts/fetch-emoji.py), and the text
 * only for one that is not: whatever the other end sent, which the core
 * does not check is an emoji at all. Or always the text, when the reader
 * asked for the system's own emoji (Settings.twemoji).
 *
 * A picker's page holds hundreds of these, built as it scrolls, so each
 * is kept cheap: the picture is decoded off the UI thread at the size it
 * is drawn, and the text is laid out only when it is what shows.
 */
Item {
    id: root

    /// The emoji, as the other end sent it or the reader picked it.
    property string emoji
    /// The edge of the square it is drawn in.
    property real size: Theme.fontSizeMedium

    /// Whether pictures are drawn at all.
    property bool pictures: Settings.twemoji === true

    /// The picture's name, or "" when there is none, or pictures are
    /// off, and the text is drawn instead.
    readonly property string picture: root.pictures ? Emoji.pictureFor(root.emoji) : ""
    /// Whether a picture is what is showing.
    readonly property bool drawn: root.picture.length > 0 && image.status !== Image.Error

    implicitWidth: root.drawn ? root.size : fallback.implicitWidth
    implicitHeight: root.size
    width: implicitWidth
    height: implicitHeight

    Image {
        id: image
        objectName: "emojiImage"
        anchors.centerIn: parent
        width: root.size
        height: root.size
        visible: root.drawn
        // 72 pixels square, decoded at the size drawn: a picker full
        // of them is a lot of texture otherwise. Off the UI thread, so a
        // row of them scrolling in does not hold up the frame.
        asynchronous: true
        sourceSize.width: Math.ceil(root.size)
        sourceSize.height: Math.ceil(root.size)
        smooth: true
        fillMode: Image.PreserveAspectFit
        source: root.picture.length > 0
                ? Qt.resolvedUrl("../art/emoji/" + root.picture + ".png") : ""
    }

    Label {
        id: fallback
        objectName: "emojiText"
        anchors.centerIn: parent
        visible: !root.drawn
        // Close to the picture's size: a font's em is taller than the
        // glyph drawn in it.
        font.pixelSize: Math.round(root.size * 0.85)
        // Whatever the other end sent: see MessageDelegate.
        textFormat: Text.PlainText
        // Nothing to lay out behind a picture.
        text: root.drawn ? "" : root.emoji
    }
}
